version: '3.4'

services:
  secure-cloud-storage:
    build: .
    container_name: secure-cloud-storage
    ports:
      - "4200:80"
    depends_on:
      - json-server
    networks:
      - app-network

  json-server:
      build:
        context: .
        dockerfile: Dockerfile.jsonserver
      container_name: json-server-container
      ports:
        - "3000:3000"
      volumes:
        - ./db.json:/data/db.json
      networks:
        - app-network

networks:
  app-network:
    driver: bridge